### ISSUE TITLE
Checklist until end of chakrathon

### ISSUE THREAD

**Issue by joyliu-q** [joyliu-q/chakrathon-select#13]
### Code
- [x] Re-add typeahead 
- [x] Write tests
- [x] Make CIs pass

### Demo
- [x] Write documentation for using this
- [x] Update prop table
- [ ] Make video (3-5 min)

**Comment by JinayJain** [comment]
- [ ] Add keyboard support for selecting an option
- [ ] Incorporate accessibility HTML attribs
- [x] Theming support for the normal select component
- [ ] Select/Option variants
- [ ] Use Storybook to demonstrate variants
